name: Hello World Workflow

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Hello World
        run: echo "Hello World Kadima 2"
        shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Goodbye
        run: echo "Goodbye Kadima"
        shell: bash
